#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
已知一个数组A[]，大小为N，其中每个数都为1～N，请求出该数组中未出现的数字和出现多次的数字。

要求是时间复杂度为O(N)，空间复杂度为O(1)
'''

def find_nums(a):
    if isinstance(a, list):
        n = len(a)
    else:
        print "not a list data"
        return

    print "the length of the list:", n
    for i in range(n):
        a[(a[i] - 1) % n] += n

    print a
    print "nun not in list: "
    for i in range(n):
        if (a[i] - 1) / n == 0:
            print i + 1,

    print "\nnum more than one time in list: "
    for i in range(n):
        if (a[i] - 1) / n > 1:
            print i + 1,

if __name__ == "__main__":
    a = [1, 1, 3, 3, 2, 5, 2]
    find_nums(a)
