#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
给定无序整数list，找到缺少的最小正整数
如:
输入[1，2，0]，输出3输入[3，4，-1，1]，输出2。

要求：O（n）时间复杂度和O（1）空间复杂度。
"""

x = [10, 2, 3, 4, 1, -1]


def intlist_find_min_lostpi(x):
    y = []
    for i in x:
        if i > 0:
            y.append(i)

    print y

    N = max(y)
    # 以最大整数创建为0的列表
    List = (N + 1) * [0]
    List[0] = 1

    # 集合去重
    y = list(set(y))
    # List的索引对应y的元素，并将List相关值设为1
    for j in y:
        List[j] += 1

    # List中首个值为0的索引即输出
    for k in range(N + 1):
        if List[k] == 0:
            return k

print intlist_find_min_lostpi(x)